export const themeStyles = {
  classic: {
    bg: "bg-gradient-to-br from-blue-50 to-indigo-100",
    text: "text-gray-900",
    primary: "text-blue-600",
    secondary: "text-indigo-600",
    accent: "bg-blue-600",
    card: "bg-white/80 backdrop-blur-sm",
    badge: "bg-blue-100 text-blue-800",
    button: "bg-blue-600 hover:bg-blue-700",
  },
  modern: {
    bg: "bg-gradient-to-br from-purple-50 to-pink-100",
    text: "text-gray-900",
    primary: "text-purple-600",
    secondary: "text-pink-600",
    accent: "bg-purple-600",
    card: "bg-white/80 backdrop-blur-sm",
    badge: "bg-purple-100 text-purple-800",
    button: "bg-purple-600 hover:bg-purple-700",
  },
  minimal: {
    bg: "bg-gradient-to-br from-gray-50 to-slate-100",
    text: "text-gray-900",
    primary: "text-slate-700",
    secondary: "text-gray-600",
    accent: "bg-slate-700",
    card: "bg-white/80 backdrop-blur-sm",
    badge: "bg-slate-100 text-slate-800",
    button: "bg-slate-700 hover:bg-slate-800",
  },
  dark: {
    bg: "bg-gradient-to-br from-gray-900 to-slate-800",
    text: "text-white",
    primary: "text-cyan-400",
    secondary: "text-blue-400",
    accent: "bg-cyan-500",
    card: "bg-gray-800/80 backdrop-blur-sm border-gray-700",
    badge: "bg-cyan-900 text-cyan-100",
    button: "bg-cyan-500 hover:bg-cyan-600",
  },
  vibrant: {
    bg: "bg-gradient-to-br from-orange-50 to-red-100",
    text: "text-gray-900",
    primary: "text-orange-600",
    secondary: "text-red-600",
    accent: "bg-orange-600",
    card: "bg-white/80 backdrop-blur-sm",
    badge: "bg-orange-100 text-orange-800",
    button: "bg-orange-600 hover:bg-orange-700",
  },
};

export type ThemeId = keyof typeof themeStyles;
