// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azietpofraodwfdmiibi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6aWV0cG9mcmFvZHdmZG1paWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDg5NzIsImV4cCI6MjA3NDE4NDk3Mn0.bkN6AD5LUombP_ZIt7gdZk86wTDYl-WoAhqfO0i9Cyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});